### ISSUE TITLE
Lychee issue with REGEX

### ISSUE THREAD

**Issue by pedrominatel** [espressif/developer-portal#148]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Provided a clear description of your suggestion.
- [X] Included any relevant context or examples.

### Issue or Suggestion Description

The links checker fails with the following link.

[https://products.espressif.com/#/product-selector?names=&filter={%22Series%22:[%22ESP32-S3%22]}](https://products.espressif.com/#/product-selector?names=&filter=%7B%22Series%22:[%22ESP32-S3%22]%7D)

After changing the link to another link (https://www.espressif.com/en/products/socs/esp32-s3) the CI still fails with the old link.

The link has been added to the ignore list as well.

**Comment by f-hollow** [comment]
More details on how it was resolved can be found in #157.
